version: "3.8"

services:
  db:
    image: postgres:14
    container_name: protocol_pg
    restart: always
    environment:
      POSTGRES_USER: protocol_user
      POSTGRES_PASSWORD: protocol_password
      POSTGRES_DB: protocoldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
